import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getLocale } from "next-intl/server";

import "./globals.css";

import Providers from "@/app/providers";

// import { redirect, routing } from "@/i18n/routing";

import { Header } from "@/components/molecules/Header";
import { Footer } from "@/components/molecules/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function LocaleLayout({
  // params,
  children,
}: LocaleLayoutProps) {
  const locale = await getLocale();

  console.log("#TESTE_1", locale);

  // const localeParam = (await params).locale;

  // const isLocaleValid = localeParam && routing.locales.includes(localeParam);

  // const locale = isLocaleValid ? localeParam : routing.defaultLocale;

  // console.log("#TESTE_1", !isLocaleValid, localeParam, locale);

  // if (!isLocaleValid) {
  // return <></>;
  // return redirect({ href: `/${localeParam ?? ""}`, locale });
  // }

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.className} min-h-screen flex flex-col antialiased bg-background-03 dark:bg-background-02`}
      >
        <Providers>
          <Header />

          {children}

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
