import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";

import Providers from "@/app/providers";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export default async function LocaleLayout({
  params,
  children,
}: LocaleLayoutProps) {
  const locale = (await params).locale;

  return (
    <html lang={locale} suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased bg-background-03 dark:bg-background-02`}
      >
        <Providers locale={locale}>
          <Header locale={locale} />

          {children}

          <Footer />
        </Providers>
      </body>
    </html>
  );
}
